version: "3"
services:
  backend:
    build:
      context: ./backend-flask
    container_name: backend
    environment:
      - SECRET_ARN=arn:aws:secretsmanager:us-east-1:265297481981:secret:AuroraCredentials-PjL1hj
      - DB_NAME=flask_db
      - CLUSTER_ARN=arn:aws:rds:us-east-1:265297481981:cluster:database-1
      - REGION=us-east-1
    ports:
      - "5000:5000"