# Docker Compose file for Backend
version: "3"
services:
  backend:
    build:
      context: ./backend-flask
    container_name: backend
    environment:
      - SECRET_ARN=arn:***
      - DB_NAME=flask_db
      - CLUSTER_ARN=arn:***
      - REGION=us-east-1
    ports:
      - "5000:5000"